import { useState } from "react";
import { downloadJson, downloadReport } from "../api";
import "./ExportReport.css";

const OPTIONS = [
  { label: "Executive summary (PDF)", kind: "executive", format: "pdf" },
  { label: "Technical report (PDF)", kind: "technical", format: "pdf" },
  { label: "Executive summary (HTML)", kind: "executive", format: "html" },
  { label: "Technical report (HTML)", kind: "technical", format: "html" },
];

// Downloads a real report generated by the backend (Jinja2 -> HTML -> PDF), or the raw analysis as JSON.
export default function ExportReport({ analysis, serverOnline }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const [open, setOpen] = useState(false);

  async function handle(option) {
    setOpen(false);
    setBusy(true);
    setError(null);
    try {
      await downloadReport(analysis, option.kind, option.format);
    } catch (e) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }

  if (!analysis) {
    return (
      <button className="export-btn" disabled title="Analyze a capture first">
        Download report
      </button>
    );
  }

  return (
    <div className="export">
      <details className="export__menu" open={open} onToggle={(e) => setOpen(e.currentTarget.open)}>
        <summary className="export-btn">{busy ? "Preparing..." : "Download report"}</summary>
        <ul className="export__list">
          {OPTIONS.map((o) => (
            <li key={o.label}>
              <button className="export__item" disabled={busy || !serverOnline} onClick={() => handle(o)}>
                {o.label}
              </button>
            </li>
          ))}
          <li>
            <button
              className="export__item"
              onClick={() => {
                setOpen(false);
                downloadJson(analysis);
              }}
            >
              Raw analysis (JSON)
            </button>
          </li>
        </ul>
        {!serverOnline && <p className="export__note">Reports are generated by the server, which is offline.</p>}
      </details>
      {error && (
        <p className="export__error" role="alert">
          {error}
        </p>
      )}
    </div>
  );
}
