"""
recommendations.py
------------------
Prioritised, actionable recommendations, a generated strongSwan configuration for a secure setup, and a
before / after score comparison.

Everything is rule-based and deterministic (no free-text generation). Each recommendation says which finding it
rests on and whether that finding was observed, inferred, declared or unknown.

The "after" score is computed by PARSING THE GENERATED SNIPPET and running it through the same scoring engine,
so the before/after comparison cannot drift from the configuration that is handed out.

The snippet uses standard strongSwan ipsec.conf syntax (ike=/esp= proposal strings, keylife, rekeymargin) but has NOT
been run against a live strongSwan in this project (Docker was unavailable): test it in a lab first.
"""

import re

from assessment import assess
from ike_parser import DH_GROUP_LABELS
from scoring_engine import score_ike_facts

PRIORITY_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}

# strongSwan proposal keywords -> what the analyzer understands
_DH_BY_NAME = {"modp1024": 2, "modp1536": 5, "modp2048": 14, "modp3072": 15, "modp4096": 16,
               "ecp256": 19, "ecp384": 20, "ecp521": 21, "curve25519": 31}
_CIPHER_BY_NAME = {"aes128gcm16": ("AES-GCM-16", 128), "aes256gcm16": ("AES-GCM-16", 256),
                   "aes128": ("AES-CBC", 128), "aes256": ("AES-CBC", 256), "3des": ("3DES", None)}

SECURE_IKE = "aes256gcm16-prfsha384-ecp384"
SECURE_ESP = "aes256gcm16-ecp384"          # the DH group in esp= turns on PFS for the child SA


def secure_ipsec_conf(mode="tunnel"):
    """A hardened strongSwan ipsec.conf connection (placeholders in <angle brackets>)."""
    return f"""# Generated by the IPsec VPN Analyzer - a starting point, NOT a tested production config.
# Replace the <placeholders>, then test in a lab (ipsec statusall, tcpdump) before using it.
config setup
    charondebug="ike 1, esp 1"

conn secure-vpn
    keyexchange=ikev2
    left=<THIS_GATEWAY_IP>
    right=<PEER_GATEWAY_IP>
    type={mode}
    authby=pubkey                 # certificates; if you must use a pre-shared key: authby=secret with 20+ random characters
    leftcert=<THIS_GATEWAY_CERT>
    ike={SECURE_IKE}!             # AES-256-GCM, SHA-384 PRF, ECP-384 (group 20)
    esp={SECURE_ESP}!             # AES-256-GCM; the ecp384 group here enables Perfect Forward Secrecy
    ikelifetime=4h
    keylife=1h
    rekeymargin=9m
    dpdaction=restart
    dpddelay=30s
    auto=start
"""


def parse_proposals(conf_text):
    """Read the ike=/esp= lines of a generated snippet back into analyzer facts (so 'after' = what we hand out)."""
    ike = re.search(r"^\s*ike=([^\s!#]+)", conf_text, re.M).group(1).split("-")
    esp = re.search(r"^\s*esp=([^\s!#]+)", conf_text, re.M).group(1).split("-")
    cipher, bits = _CIPHER_BY_NAME[ike[0]]
    dh = _DH_BY_NAME[ike[-1]]
    esp_dh = _DH_BY_NAME.get(esp[-1])
    mode = re.search(r"^\s*type=(\w+)", conf_text, re.M).group(1)
    return {"cipher": cipher, "key_length_bits": bits, "dh_group": dh, "pfs": esp_dh is not None, "mode": mode}


def _item(rank_id, priority, title, action, why, status, confidence=None, standards=None, config_hint=None):
    return {"id": rank_id, "priority": priority, "title": title, "action": action, "why": why,
            "based_on": {"status": status, "confidence": confidence}, "standards": standards or [], "config_hint": config_hint}


def build_items(ctx, findings, exposure, compliance):
    by = {f["id"]: f for f in findings}
    items = []
    dh, cipher, pfs, mode = by["dh_group"], by["cipher"], by["pfs"], by["mode"]
    facts = ctx["facts"]["ike_sa"]

    # ---- AH only: no confidentiality at all
    prot = by["protocol"]
    if prot["value"].startswith("AH"):
        items.append(_item("protocol", "Critical", "Use ESP: AH does not encrypt",
                           "Replace AH with ESP using an AEAD cipher (aes256gcm16). AH only authenticates packets; the payload stays readable.",
                           "Anyone on the path can read the traffic.", prot["status"], prot["confidence"], [], "esp=aes256gcm16-ecp384!"))
    elif prot["value"] == "ESP + AH":
        items.append(_item("protocol", "Low", "Consider dropping AH on top of ESP",
                           "ESP with an AEAD cipher already provides integrity; AH in addition adds overhead and complexity.",
                           "Simplifies the configuration.", prot["status"], prot["confidence"]))

    # ---- key exchange
    if dh["rating"] == "weak":
        items.append(_item("dh", "High", "Replace the weak Diffie-Hellman group",
                           f"Change the key-exchange group from {dh['value']} to an elliptic-curve group (19 or 20) or MODP 3072-bit or larger.",
                           "Groups below 2048 bits give less than 112 bits of security strength.", dh["status"], dh["confidence"],
                           ["NIST SP 800-131A Rev. 2", "NIST SP 800-57"], f"ike=...-{'ecp384'}!  (and the same group in esp= for PFS)"))
    elif dh["rating"] == "medium":
        items.append(_item("dh", "Medium", "Move to an elliptic-curve key exchange",
                           f"{dh['value']} is acceptable today but has little safety margin; use group 19 or 20.", "Longer safety margin, faster handshakes.",
                           dh["status"], dh["confidence"], [], "ike=...-ecp384!"))
    elif dh["status"] == "unknown":
        items.append(_item("dh", "Medium", "Confirm the key-exchange group",
                           "The DH group is only visible in the cleartext IKE_SA_INIT, which is not in this capture. Check the gateway configuration "
                           "(or recapture from before the tunnel comes up).", "It carries 15% of the assessment and 40% of the raw score.", "unknown"))

    # ---- cipher
    cname = facts["cipher"]
    if cname == "3DES":
        items.append(_item("cipher", "Critical", "Stop using 3DES", "Replace 3DES with AES-256-GCM.",
                           "Three-key TDEA encryption is not acceptable after 2023.", cipher["status"], cipher["confidence"], ["NIST SP 800-131A Rev. 2"],
                           "esp=aes256gcm16-ecp384!"))
    elif cname == "AES-CBC" or (cipher["status"] == "inferred" and "CBC" in str(cipher["value"])):
        items.append(_item("cipher", "Medium", "Prefer an AEAD cipher (AES-256-GCM) over AES-CBC",
                           "Use aes256gcm16 for IKE and ESP: it protects integrity and confidentiality in one step and needs no separate HMAC.",
                           "Removes padding-oracle style risks of CBC + HMAC and gives a 256-bit key.", cipher["status"], cipher["confidence"],
                           ["RFC 8221 (AES-GCM-16 is mandatory to implement)"], "esp=aes256gcm16-ecp384!"))
    elif cipher["status"] == "unknown":
        items.append(_item("cipher", "Low", "Confirm the cipher", "The cipher could not be established from this capture; check the gateway configuration.",
                           "Part of the assessment could not be completed.", "unknown"))

    # ---- PFS
    if pfs["value"] == "disabled":
        items.append(_item("pfs", "High", "Enable Perfect Forward Secrecy",
                           "Add a DH group to the ESP proposal so every rekey performs a fresh key exchange.",
                           "Without it, one leaked key can expose all traffic protected by that SA and its successors.", pfs["status"], pfs["confidence"],
                           [], "esp=aes256gcm16-ecp384!"))
    elif pfs["status"] == "unknown":
        items.append(_item("pfs", "Medium", "Verify that Perfect Forward Secrecy is enabled",
                           "PFS is negotiated inside encrypted IKE messages and cannot be seen in a capture. Confirm the ESP proposal contains a DH group "
                           "(for strongSwan: esp=...-ecp384!) with `ipsec statusall`.", "It carries 15% of the assessment.", "unknown",
                           None, [], "esp=aes256gcm16-ecp384!"))

    # ---- mode
    if mode["value"] == "transport":
        items.append(_item("mode", "Low", "Use tunnel mode unless host-to-host transport mode is required",
                           "Tunnel mode encrypts the original IP header and hides the real endpoints behind the gateways.",
                           "Reduces what an eavesdropper learns about who talks to whom.", mode["status"], mode["confidence"], [], "type=tunnel"))

    # ---- key lifetime / replay
    life, replay = by["key_lifetime"], by["replay"]
    if life["rating"] == "weak":
        items.append(_item("lifetime", "Medium", "Shorten the SA lifetime", "Set keylife=1h (child SA) and ikelifetime=4h or shorter.",
                           "Limits how much data one key protects.", life["status"], life["confidence"], [], "keylife=1h"))
    elif life["status"] == "unknown":
        items.append(_item("lifetime", "Low", "Set and verify a short SA lifetime",
                           "Set keylife=1h and ikelifetime=4h, then verify with a capture at least twice as long as keylife so a rekey is observed.",
                           "The lifetime cannot be observed unless a rekey happens inside the capture.", "unknown", None, [], "keylife=1h"))
    if replay["rating"] == "weak":
        items.append(_item("replay", "High", "Investigate repeated ESP sequence numbers",
                           "Repeated sequence numbers were seen. Check for replayed packets, and confirm the receiving gateway keeps its anti-replay window enabled.",
                           "Anti-replay relies on strictly increasing sequence numbers.", replay["status"], replay["confidence"]))

    # ---- capture quality
    if by["ike_version"]["status"] == "unknown":
        items.append(_item("capture", "Medium", "Capture from before the tunnel comes up",
                           "Start the capture, then bring the tunnel up (for example `tcpdump -w` first, then `ipsec up`), so IKE_SA_INIT is included.",
                           "It is the only place the cipher and DH group are visible; without it the assessment stays incomplete.", "unknown"))

    # ---- metadata exposure
    tr = ctx.get("traffic")
    if tr and tr["class"] != "unrecognised" and (tr.get("confidence") or 0) >= 0.8:
        items.append(_item("metadata", "Medium" if exposure["level"] == "HIGH" else "Low", "Reduce the traffic-type leak",
                           f"An eavesdropper can tell this traffic is {tr['label'].lower()} ({tr['confidence']:.0%}). Padding packets to fixed sizes and adding "
                           "dummy traffic reduces this; see the defence simulation for the effect measured on this project's dataset.",
                           "IPsec encrypts payloads but not packet sizes or timing.", "inferred", tr["confidence"], [],
                           "(not an ipsec.conf option - needs padding support, e.g. ESP TFC padding, or an overlay)"))

    items.sort(key=lambda i: PRIORITY_ORDER[i["priority"]])
    for n, it in enumerate(items, 1):
        it["rank"] = n
    return items


def _after(ctx, raw_before):
    """Score of the generated configuration, computed by parsing the snippet and running the normal engine."""
    target = parse_proposals(secure_ipsec_conf("tunnel"))
    facts = {"ike_version": "2.0", "mode": target["mode"],
             "ike_sa": {"cipher": target["cipher"], "key_length_bits": target["key_length_bits"], "dh_group": target["dh_group"]},
             "esp_sa": {"pfs": target["pfs"]}}
    ratings = {k: v["rating"] for k, v in score_ike_facts(facts)["factors"].items()}
    base = score_ike_facts(facts)["overall_score"]

    def run(sources, fp, seq):
        c = {"facts": dict(facts, _conf={}, _consistency=[]), "sources": sources, "conf": {"mode": 0.99, "cipher": 0.99}, "ike": {"ike_version": "2.0"},
             "fp": fp, "seq": seq, "traffic": ctx.get("traffic"), "ratings": ratings}
        return assess(c, base)

    passive_fp = {"esp_packets": 100, "cipher_family": {"value": "GCM-like", "confidence": 0.97}, "mode": {"value": "tunnel", "confidence": 0.99},
                  "integrity_tag": {"candidates": []}}
    seq_ok = {"sa_lifetime": {"observable": False, "note": "not observable"}, "replay_protection": {"status": "evidence_present", "evidence": "e"}}
    # (a) a new PASSIVE capture that includes the cleartext IKE_SA_INIT: PFS and authentication remain invisible
    passive = run({"cipher": "observed", "dh_group": "observed", "pfs": "unknown", "mode": "inferred"}, passive_fp, seq_ok)
    # (b) reading the gateway configuration directly: every fact is known
    review = run({"cipher": "declared", "dh_group": "declared", "pfs": "declared", "mode": "declared"}, None, None)
    for f in review["findings"]:          # a direct configuration review establishes each of these
        f["status"] = "observed"
        f["confidence"] = 1.0
    from assessment import completeness, apply_cap
    review_pct, _ = completeness(review["findings"])
    review_final, review_cap, _ = apply_cap(base, review_pct, review["findings"])
    return target, base, passive, (review_final, review_pct)


def before_after(ctx, before):
    target, raw_after, passive, (review_score, review_pct) = _after(ctx, before["raw_score"])
    from contract import risk_from_score

    def snap(score, raw, pct):
        return {"score": score, "raw_score": raw, "risk_level": risk_from_score(score), "completeness_pct": pct}
    return {
        "label": "Projection - what the tool would report if the recommended configuration were applied (not a measurement)",
        "configuration": {"recommended": parse_proposals(secure_ipsec_conf("tunnel"))},
        "before": snap(before["score"], before["raw_score"], before["completeness_pct"]),
        "after_passive_capture": {**snap(passive["score_after_cap"], raw_after, passive["completeness_pct"]),
                                  "assumption": "a new capture that includes the cleartext IKE_SA_INIT; PFS, authentication and key lifetime stay invisible to a passive capture, "
                                                "which is why even a perfect configuration cannot reach 100 from a capture alone"},
        "after_config_review": {**snap(review_score, raw_after, review_pct),
                                "assumption": "the gateway configuration is read directly, so every fact is known"},
    }


def recommend(ctx, assessment, score, raw_score):
    items = build_items(ctx, assessment["findings"], assessment["metadata_exposure"], assessment["compliance"])
    before = {"score": score, "raw_score": raw_score, "completeness_pct": assessment["completeness_pct"]}
    return {
        "items": items,
        "secure_config": {"format": "strongSwan ipsec.conf", "text": secure_ipsec_conf("tunnel"),
                          "verified": False,
                          "note": "Standard strongSwan syntax, but NOT verified against a running strongSwan in this project (Docker was unavailable). "
                                  "Test it in a lab first; replace every <placeholder>."},
        "before_after": before_after(ctx, before),
    }
