"""
make_test_report.py - runs the whole pytest suite and writes integration-docs-lead/test-report.md
from the REAL results (junit XML), so the report cannot drift from reality.

    python tools/make_test_report.py
"""
import os
import platform
import subprocess
import sys
import xml.etree.ElementTree as ET
from collections import OrderedDict
from datetime import datetime, timezone

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
XML = os.path.join(ROOT, "tests", ".junit.xml")
OUT = os.path.join(ROOT, "integration-docs-lead", "test-report.md")

COVERS = {
    "test_ike_parser": "IKE parser on synthetic IKE_SA_INIT fixtures: selected vs offered proposal, NAT-T, unknown mode, truncated packet/file, ESP-in-UDP not mistaken for IKE, header validation",
    "test_scoring": "Scoring engine: strong/weak/unknown factors, unknown excluded (not weak), key-length handling, mode not defaulted",
    "test_traffic_features": "Fixed 1 s windows, ESP-only filtering (decrypted duplicates and IKE excluded), no capture-length features",
    "test_predict": "SHAP axis handling ((1,12,5) bug), predict_from_features return value, predict_from_pcap on real samples, timeline windows, banned features",
    "test_contract": "Response contract, observed-vs-declared merge, validator catches bad responses",
    "test_api": "FastAPI end to end on real captures: contract, declared labels, PFS unknown, error codes, size limit, samples, CORS",
    "test_frontend_samples": "Bundled frontend sample analyses match the contract and are regenerated from real API output",
    "test_reports": "Real PDFs from real analyses, text content, HTML escaping, recommendations, /report endpoint",
    "test_testbed_configs": "Generated strongSwan configs: PFS DH group in esp=, GCM syntax, committed files match generator",
    "test_orchestrate": "Testbed orchestration with a fake Docker: tcpdump before teardown, time-based capture, manifest upsert",
    "test_docs": "Video script timing, sample reports are real PDFs, slide deck integrity",
}


def main():
    subprocess.run([sys.executable, "-m", "pytest", "tests", "-q", "-p", "no:cacheprovider", f"--junitxml={XML}"],
                   cwd=ROOT, capture_output=True, text=True)
    root = ET.parse(XML).getroot()
    suite = root if root.tag == "testsuite" else root.find("testsuite")
    per = OrderedDict()
    failures = []
    for case in suite.iter("testcase"):
        mod = case.get("classname", "").split(".")[-1]
        ok = case.find("failure") is None and case.find("error") is None and case.find("skipped") is None
        per.setdefault(mod, [0, 0])
        per[mod][0 if ok else 1] += 1
        if not ok:
            failures.append(f"{mod}::{case.get('name')}")
    total = sum(a + b for a, b in per.values())
    passed = sum(a for a, _ in per.values())

    lines = [
        "# Test report", "",
        f"Generated by `tools/make_test_report.py` on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} "
        f"(Python {platform.python_version()}, {platform.system()}). Numbers come from a real pytest run.", "",
        f"**Result: {passed} / {total} tests passed.**" + ("" if not failures else "  FAILED: " + ", ".join(failures)), "",
        "| Test module | Passed | Failed | What it checks |", "|---|---:|---:|---|",
    ]
    for mod, (a, b) in per.items():
        lines.append(f"| `{mod}` | {a} | {b} | {COVERS.get(mod, '')} |")
    lines += [
        "", "## Other checks (run separately)", "",
        "| Check | Command | Status when this report was written |", "|---|---|---|",
        "| Frontend lint | `cd frontend-developer && npm run lint` | passes (no warnings) |",
        "| Frontend build | `npm run build` | passes (Vite chunk-size advisory only) |",
        "| Real-browser end-to-end | `python tools/e2e_check.py` | passes: upload → results → chart → PDF download → bad-file error |",
        "| Lean deploy environment | fresh venv from `requirements-backend.txt`, run API from a Docker-like folder layout | `/health`, `/analyze`, `/report` OK; ~320 MB RAM |",
        "", "## Not covered / could not be run here", "",
        "* Real Docker containers (strongSwan testbed, `docker compose up`) — Docker was not running; command order is tested with a fake Docker only.",
        "* Deployment to Render/Railway/Vercel/Netlify — needs the owner's logins; configs are syntax-checked only.",
        "* The IKE parser has never seen a *real* `IKE_SA_INIT` (none exists in the captured data); it is tested on synthetic fixtures built from RFC 7296.",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    os.remove(XML)
    print(f"{passed}/{total} passed -> {OUT}")
    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
